### ISSUE TITLE
Can not access the kernel32 GetModuleHandleW() function

### ISSUE THREAD

**Issue by jfongattw** [MatthieuDartiailh/pyclibrary#37]
My environment is: Windows Vista, Python 3.4 and pyclibrary-0.1.4

D:\Works\Python\pyclibrary-0.1.4>py
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyclibrary import CParser, CLibrary
>>> p = CParser(cache=r'd:\Works\Python\pyclibrary-master\pyclibrary\headers\WinDefs.cache', check_cache_validity=False)
>>> lib0 = CLibrary(r'c:\Windows\System32\Kernel32.dll', p, convention='windll')
>>> lib0['functions']['GetModuleHandleW']
Type((Type(('HMODULE', '__stdcall'), type_quals=(('__',), None)), (('lpModuleName', Type(('LPCWSTR',), type_quals=(('__',),)), None),)))
>>> ret = lib0.GetModuleHandleW('user32.dll')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Works\Python\pyclibrary-0.1.4\pyclibrary\c_library.py", line 230, in __getattr__
    obj = self(k, n)
  File "D:\Works\Python\pyclibrary-0.1.4\pyclibrary\c_library.py", line 210, in __call__
    self._objs_[typ][name] = self._make_obj_(typ, name)
  File "D:\Works\Python\pyclibrary-0.1.4\pyclibrary\c_library.py", line 272, in _make_obj_
    return self._get_function(n)
  File "D:\Works\Python\pyclibrary-0.1.4\pyclibrary\c_library.py", line 338, in _get_function
    func_name, self._lock_calls_)
  File "D:\Works\Python\pyclibrary-0.1.4\pyclibrary\c_library.py", line 413, in __init__
    self.sig[1] = [s for s in sig[1] if s[1] != ('void',)]
IndexError: tuple index out of range
>>>

Best Regards,
Jach Fong

**Comment by MatthieuDartiailh** [comment]
Thanks for the report. I don't have access to a windows box currently. I will try to investigate when I do, hopefully before the end of August. Do not hesitate to ping me.
